[package]
name = "i3-msg"
version = "0.1.0"
authors = ["Pepe García <pepe@pepegar.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.0"